raven_to_wav:
  annotations_file: test_data/annotation_txt_files/vocalizations/test_chimp_annotations.csv
  species: chimpanzee
  wavpath: test_data/mefou/
  outputdir: test_data/processed_wav_files/vocalizations/
  recID: 2C
  min_sig_len: 0.2
  bg_padding_len: 0.05
  startindex: 0
  createframes: False

condensation:
  input: test_data/original_recordings/mefou
  output-csv: test_data/condensed_wav_files/timestamps.csv
  output-signal: test_data/condensed_wav_files/test_out.wav
  frequencies: [(200, 1000)]
  volume: (20, 30)

synth_pipeline_vocalizations:
  input_dir_background_original: None
  background_annotation_dir: None
  output_dir_background: None
  input_dir_temp_background: test_data/synthetic_intermediate/background
  overview_temp_background: test_data/synthetic_intermediate/overviews/background_orig_test.json
  input_dir_vocalizations: test_data/processed_wav_files/vocalizations
  overview_vocalizations: test_data/synthetic_intermediate/overviews/vocalizations_test.json
  input_dir_background: test_data/processed_wav_files/background
  overview_background: test_data/synthetic_intermediate/overviews/background_test.json
  output_vocalizations: test_data_dir/synth_data/vocalizations
  output_background: test_data_dir/synth_data/background

feature_extraction:
  input_dir: test_data_dir/synth_data # this is not used
  feature_dir: test_data/features/train/
  sample_rate: 48000
  window_length: [750]
  hop_length: [376]
  n_mel: [64]
  low_cut: 100
  high_cut: 2000
  pcen:
    gain: 0.98
    bias: 2
    power: 0.5
    time_constant: 1.5
    eps: 0.000001

feature_extraction_svm:
  defaults:
    frame_length: 24000
    hop_length: 12000
    cores: 8
    filter: [100, 2000, 5]
  jobs:
    test:
      input_dir: ./test_input/
      output_dir: ./test_output/test_24000.csv
      label1: chimpanze
      label2: test
    chimpanze_mefou:
      input_dir: test_data/processed_wav_files/vocalizations/
      output_dir: test_data/features/train/chimpanze_mefou_24000.csv
      label1: chimpanze
      label2: train
    chimpanze_synthetic:
      input_dir: test_data/synth_data/vocalizations/
      output_dir: test_data/features/train/chimpanze_synthetic_24000.csv
      label1: chimpanze
      label2: train
    background_mefou:
      input_dir: test_data/processed_wav_files/background/
      output_dir: test_data/features/train/background_mefou_24000.csv
      label1: background
      label2: train
    background_synthetic:
      input_dir: test_data/synth_data/background/
      output_dir: test_data/features/train/background_synthetic_24000.csv
      label1: background
      label2: train


model_training:
  model: svm #cnn10 cnn12
  output_dir: test_data/models/svm/
  augmentation: True
  set_threshold: False

evaluate:
  model: svm #cnn10 cnn12
  model_dir: test_data/models/svm/
  feature_dir: test_data/features/test/
  output_dir: test_data/models/svm/

predict:
  model: svm #cnn10 cnn12
  model_dir: test_data/models/svm/
  feature_dir: test_data/features/test/
  output_dir: test_data/models/svm/


model_setting:
  num_channels: 3
  init_mode: "he_normal" # "glorot_uniform"
  dropout_rate: 0.5
  weight_constraint: 4
  weight_decay: 0.001
  epochs: 20
  batch_size: 32
  learning_rate: 0.0001
  samples_per_epoch: 11200
  frames_per_chunk: 64



