project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - getting-started.qmd
    - workflow.qmd
    - prediction.qmd
    - methods.qmd
    - wav-processing.qmd
    - feature-extraction.qmd
    - condensation.qmd
    - classifier.qmd
    - model_comparison.ipynb

website:
  title: Animal Sounds
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source code
            url:  https://github.com/UtrechtUniversity/animal-sounds
          - text: Report an issue
            url:  https://github.com/UtrechtUniversity/animal-sounds/issues
    left:
      - href: index.qmd
        text: Home
      - href: getting-started.qmd
        text: Getting Started
      - href: workflow.qmd
        text: Training Workflow
      - href: prediction.qmd
        text: Prediction
      - href: methods.qmd
        text: Methods
      - href: model_comparison.ipynb
        text: Model Comparison

format:
  html:
    theme: flatly
    toc: true
    code-fold: show

execute:
  enabled: true
  echo: true
  warning: false
  freeze: false
