# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'poetry'
      - name: Install dependencies
        run: poetry install
      - name: Run black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./bioacoustics"
      - name: Lint with flake8
        run: |
          poetry run flake8 bioacoustics/
      - name: Check if documentation builds.
        run: |
          sudo apt-get install -y libsndfile-dev
          cd docs; poetry run make html SPHINXOPTS="-W --keep-going"
